//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoreMe.DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_Login
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string UserIPAddress { get; set; }
        public Nullable<System.DateTime> LoginDateTime { get; set; }
        public Nullable<System.DateTime> AccessDateTime { get; set; }
        public Nullable<System.DateTime> LockDateTime { get; set; }
        public Nullable<System.DateTime> PasswordChangeDateTime { get; set; }
        public Nullable<int> IsActive { get; set; }
    }
}
