//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoreMe.DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CALLModel
    {
        public long ID { get; set; }
        public int Status { get; set; }
        public long UserID { get; set; }
        public Nullable<long> TotalCallCount { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<long> OutCallCount { get; set; }
        public Nullable<long> OutMissedCallCount { get; set; }
        public Nullable<decimal> OutCallMinute { get; set; }
        public Nullable<long> InCallCount { get; set; }
        public Nullable<long> InMissedCallCount { get; set; }
        public Nullable<decimal> InCallMinute { get; set; }
        public Nullable<long> OutCallForeignCount { get; set; }
        public Nullable<decimal> OutCallForeignMinute { get; set; }
        public Nullable<long> InCallForeignCount { get; set; }
        public Nullable<decimal> InCallForeignMinute { get; set; }
        public Nullable<long> OutCallRoamingCount { get; set; }
        public Nullable<decimal> OutCallRoamingMinute { get; set; }
        public Nullable<long> InCallRoamingCount { get; set; }
        public Nullable<decimal> InCallRoamingMinute { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<long> InsertUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> UpdateUser { get; set; }
    }
}
