//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoreMe.DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AppGroupInformation
    {
        public long ID { get; set; }
        public int Status { get; set; }
        public int CategoryType { get; set; }
        public string CategoryName { get; set; }
        public Nullable<decimal> PriceUsage { get; set; }
        public Nullable<decimal> PointUsage { get; set; }
        public Nullable<decimal> PriceCount { get; set; }
        public Nullable<decimal> PointCount { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<long> InsertUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> UpdateUser { get; set; }
    }
}
