//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoreMe.DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SMSReport
    {
        public long ID { get; set; }
        public int Status { get; set; }
        public long UserID { get; set; }
        public long SMSModelID { get; set; }
        public long SMSDetailID { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> OutMsjCountSame { get; set; }
        public Nullable<int> OutMsjCountOther { get; set; }
        public Nullable<int> OutMsjForeignCount { get; set; }
        public Nullable<int> OutMsjRoamingCount { get; set; }
        public Nullable<int> InMsjCount { get; set; }
        public Nullable<int> InMsjForeignCount { get; set; }
        public Nullable<int> InCallRoamingCount { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<long> InsertUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> UpdateUser { get; set; }
    }
}
