//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoreMe.DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AccessRight
    {
        public int ID { get; set; }
        public Nullable<int> Status { get; set; }
        public int UserId { get; set; }
        public string Controller { get; set; }
        public string ControllerDesc { get; set; }
        public string Action { get; set; }
        public string ActionDesc { get; set; }
        public int HasAccess { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<int> InsertUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateUser { get; set; }
    }
}
