//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoreMe.DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SMSModel
    {
        public long ID { get; set; }
        public int Status { get; set; }
        public long UserID { get; set; }
        public Nullable<long> TotalMessageCount { get; set; }
        public Nullable<long> ShortMessageCount { get; set; }
        public Nullable<long> OutMessageCount { get; set; }
        public Nullable<long> InMessageCount { get; set; }
        public Nullable<long> OutMessageForeignCount { get; set; }
        public Nullable<long> InMessageForeigCount { get; set; }
        public Nullable<long> OutMessageRoamingCount { get; set; }
        public Nullable<long> InMessageRoamingCount { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<long> InsertUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> UpdateUser { get; set; }
    }
}
