//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoreMe.DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NetConsumeDetail
    {
        public long ID { get; set; }
        public int Status { get; set; }
        public long NetModelID { get; set; }
        public long UserID { get; set; }
        public long Source_EVID { get; set; }
        public Nullable<long> Operator_EVID { get; set; }
        public string OperatorName { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int Day { get; set; }
        public Nullable<int> Hour { get; set; }
        public Nullable<int> Minute { get; set; }
        public Nullable<decimal> Consumed { get; set; }
        public Nullable<decimal> DownloadSpeed { get; set; }
        public Nullable<decimal> UploadSpeed { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<long> InsertUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> UpdateUser { get; set; }
    }
}
